[package]
name = "raw-to-jpeg"
version = "0.1.0"
edition = "2021"

[dependencies]
make87 = { version = "0.1.0-dev1", features = ["zenoh","protobuf"] }
make87_messages = "0.2.6"
anyhow = "1.0.98"
tokio = "1.45.0"
turbojpeg = "1.3.2"
env_logger = "0.11.8"
log = "0.4.27"
